name: flutter_panutan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.1.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    #Widget
    cupertino_icons: ^1.0.2
    shimmer: ^3.0.0
    fluttertoast: ^8.2.2
    webview_flutter: ^4.2.4
    local_auth: ^2.1.7

    #Data
    shared_preferences: ^2.2.1
    http: ^1.1.0
    dio: ^5.3.2

    #Asset
    flutter_svg: ^2.0.7
    freezed_annotation: ^2.4.1

    #Helper
    flutter_bloc: ^8.1.3
    dartz: ^0.10.1
    get_it: ^7.6.2
    bloc: ^8.1.2
    logger: ^2.0.2+1
    
    #Util
    money_formatter: ^0.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.6
    flutter_gen_runner: ^5.3.1
    freezed: ^2.4.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  # - family: Ubuntu
  #   fonts:
  #     - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
  #       weight: 600
  

# Flutter Gen Asset Configs
flutter_gen:
  output: lib/assets_gen/

  integrations:
    flutter_svg: true
    # lottie: false

  assets:
    enabled: true
    outputs:
      class_name: MyAssets

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily